### ISSUE TITLE
Another Couple Errors I found with Error-Magnifier (name tags)

### ISSUE THREAD

**Issue by HowNotToGame** [SirDoggyJvla/Zomboid-Forge#2]
Only found two I think both correlating to name tags.
Sandbox settings are default apocalypse with name tags always shown enabled.
Error Codes: 
Error 1:
`function: DrawNameTag -- file: ZomboidForge_visuals.lua line # 385 | MOD: Zomboid Forge
function: UpdateNametag -- file: ZomboidForge_visuals.lua line # 322 | MOD: Zomboid Forge
function: OnTick -- file: ZomboidForge.lua line # 201 | MOD: Zomboid Forge
java.lang.RuntimeException: __div not defined for operands in DrawNameTag
    at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:676)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:92)
    at zombie.gameStates.IngameState.updateInternal(IngameState.java:1624)
    at zombie.gameStates.IngameState.update(IngameState.java:1333)
    at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
    at zombie.GameWindow.logic(GameWindow.java:298)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:681)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`
Error 2:
`function: DrawNameTag -- file: ZomboidForge_visuals.lua line # 385 | MOD: Zomboid Forge
function: UpdateNametag -- file: ZomboidForge_visuals.lua line # 322 | MOD: Zomboid Forge
function: OnTick -- file: ZomboidForge.lua line # 201 | MOD: Zomboid Forge
`

modlist will be posted below. 

![Modlist2](https://github.com/user-attachments/assets/95361603-536d-4650-882d-abb50109c923)

**Comment by SirDoggyJvla** [comment]
Fixed in update 2.1.2

**Comment by SimKDT** [comment]
Fixed in update 2.1.2

Was related to the tick duration of nametags
